### ISSUE TITLE
Upgrade from node16 to node20

### ISSUE THREAD

**Issue by SwitzerChees** [antongolub/action-setup-bun#96]
## Issue type

- [x] question

## Specifications

We have started to get warnings in CI related to the deprecation of Node 16.
Any ideas to update the action to node 20?

![image](https://github.com/antongolub/action-setup-bun/assets/26026462/2c60b27c-0200-434b-ba8d-930b3f6336a6)

Thanks by the way for this cool and useful action because it allows much better caching options than the "official one".

**Comment by antongolub** [comment]
Thanks for highlighting this. I'll take care.
